-- ISNULL
SELECT ISNULL(NULL, 'Une valeur');

-- CAST / CONVERT
SELECT CAST(GETDATE() AS VARCHAR) AS [Cast], CONVERT(VARCHAR, GETDATE()) AS [Convert], CONVERT(VARCHAR, GETDATE(), 103) AS [ConvertWithFormat];

-- Dates
---- DATEADD
SELECT DATEADD(SECOND, 72000, GETDATE()) AS [Maintenant + 20h]

---- DATEDIFF
SELECT DATEDIFF(SECOND, GETDATE(), DATEADD(SECOND, -12, GETDATE())) AS [Ca doit affichier -12]

---- DATEPART
SELECT DATEPART(WEEK, GETDATE()) AS [Semaine de l'année], DATEPART(WEEKDAY, GETDATE()) AS [Jour de la semaine]
